### PR TITLE
Generic socket

### PR DESCRIPTION
**Pull request by coreyeng**
Added support for configuring an unknown toolchain (vendor). This was developed for ncsim, which, as part of cadence, probably could have its own vendor, but for now, I used it to prototype a generic tester. This requires you to setup at least a <code>post_run_start_block</code> process, which should be system commands (or anything, really) that starts up the testbench and passes it the socket. An example, using <code>ncsim</code>, is:

~~~ruby
OrigenSim.generic(startup_timeout: 900) do |sim|
  sim.testbench_top 'na_origen'
  sim.post_run_start_block do |s|
    pid = Process.spawn("ncsim na_origen -loadpli origen.so:bootstrap +socket+#{s.socket_id}")
    puts "Spawning process: #{pid}"
  end
end
~~~

Updated the README, but plan to do more thorough docs once we start a website for OrigenSim.

A few other, more minor updates:
* Added some shortcut methods to instantiate the tester. E.g., <code>OrigenSim.generic(...)</code> instead of OrigenSim::Tester.new(vendor: :generic, ...)</code> or <code>OrigenSim.cadence(...)</code> instead of <code>OrigenSim::Tester.new(vendor: :cadence, ...)</code>.
* The tester and <code>simulator::configure</code> uses the Collector, with the options taking precedence. So, either hash or block syntax is supported.
* Updated Origen version to use the version with the Collector.
* Added an option to configure the testbench name. This will propagate through all the system calls. <code>origen</code> is the default.
* Added a similar option when using <code>origen sim:build</code>, i.e., <code>origen sim:build --testbench NAME</code> which will compile the VPI using that name. Default is <code>origen</code>.
* Added a <code>pack</code> and <code>unpack</code> method to just compress and uncompress the snapshot without checking it in. Plan to combine with <code>ci/co</code>,  but kept it in for now.
* Added a bootstrap method to the VPI, to be used if the VPI isn't auto-booted (it is in <code>irun</code>, but is not in <code>ncsim</code>.

### CODE REVIEW

**Comment by coreyeng** [comment]
I can update the README to include the ncsim example. I was trying to keep it in generic terms and am thinking we might add a ncsim vendor later, if our other teams don't update to irun soon. But, I agree.

I'll need to pull this down to merge and re-test with master, so I'll update the README with the ncsim example as well.

**Comment by ginty** [comment]
Yeah, just having a look at how this is implemented with respect to the other PR about better process management, you may need to rethink how the pre/post run blocks are handled.
I don't think it should be used as in this example where the user spawns the process and generates a PID, OrigenSim should manage that and this should be more about the user providing an alternative command to run.

**Comment by coreyeng** [comment]
Yes, I agree. I'll look into that as well. I still like the idea of being able to do some arbitrary setup and tear down, but OrigenSim should handle the command that's supposed to start the testbench.

**Comment by coreyeng** [comment]
This branch is actually used in a few of our applications and since I'm going to make non-backwards compatibility changes, I'm going to leave this branch alone for now, push to a copy of the branch, PR that one, and then adjust the applications accordingly. I'll delete both branches when merged and both apps are moved to the new release.

Thanks.

@chrisnappi

**Pull request closed without merging**
