### PR TITLE
Add Support for LSF and Parallel Simulations

### PR DESCRIPTION
**Pull request by ginty**
This update adds full support for running OrigenSim simulations on the LSF, however some minor changes in operation were required to enable this.

Firstly it became clear that generating all patterns into a wave called 'origen' was a bad idea if you want to run multiple simulations at the same time, so now the created waves are named after the pattern.

It was also necessary to better support the concept of multiple simulations, even when not running on the LSF, and the previous default of running multiple patterns as concatenated within a single simulation has changed.

Now if you run this:

~~~text
origen g my_pat_1 my_pat_2
~~~

it will run them sequentially as separate simulations, creating two waveforms named after each pattern.

To get the previous behavior of combining them into a single simulation you now need to add a `--flow` option:

~~~text
origen g my_pat_1 my_pat_2 --flow my_flow
~~~

This will simulate the given patterns back-back and dump them to a waveform named after the `flow` option, in this case "my_flow".

Program generation works the same as before, but now the generated wave will be named after the flow and not called 'origen'.

The LSF switches now work as per conventional pattern generation and everything seems to work when running the simulations remotely.

If the `--flow` switch is supplied then the patterns will be submitted as a single job for sequential simulation, otherwise they will be split up into multiple concurrent jobs.

Some fairly significant internal re-arch was required to enable this, most significantly is the addition of a new class called `OrigenSim::Simulation`. This class is now responsible for much of what used to be in `OrigenSim::Simulator`, and specifically the things which should be manged on a per-simulation basis. This is basically error and log tracking and managing the communication sockets.
The `Simulator` class remains in charge of handling the specifics of the different simulator types and managing the Origen -> VPI communication protocol.

Other feature additions:

* The Origen process will now exit with a `1` (std unix fail code) if any simulations fail, thereby enabling 3rd party tools to monitor the result of simulations performed in a regression test - e.g. a Bamboo agent.

* Added an API to allow application code to force a simulation fail, which piggy backs on the way that log output from the simulator can make the simulation result be classed as a fail:

~~~ruby
# When running in simulation, verify this node which is not observable on the tester
if tester.sim?
  if tester.simulator.peek("origen.dut.path.to.some.node").to_i == 1
    OrigenSim.error "The internal blah warning was asserted!"
  end
end
~~~

* Further improvements to the simulation monitor wrapper. In the course of developing this update I noticed that I was still able to create some zombie processes. I have so far been unable to create any with this further improvement which takes better account of the possibility of the socket read hanging within the monitor.

### CODE REVIEW

**Comment by redxeth** [comment]
We've had issues in our app using origen_sim beyond 0.7.0.  Will try this one to see.

**Comment by ginty** [comment]
@redxeth, probably your design needs to be recompiled with the testbench and extension from the newer version.
0.8.0 changed the internal time base from ns to ps and while I tried to make it backwards compatible, maybe it's not and it would not work well if Origen and the simulation are working from different time bases.

**Comment by redxeth** [comment]
@ginty thanks will try it.  Have a few other balls in the air just now.  Including a crystal one...

**Comment by ginty** [comment]
Going ahead with merge based on it working as described in a pilot application.

**Pull request merged**
